//! Main file generated by Qt
/*! \file main.cpp
 *
 */
#include "mainwindow.h"
//#include "boxes.h"

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    a.setStyle("fusion");
    w.show();
    return a.exec();
}
